plugins { id 'com.android.application' }

android {
    namespace 'com.abe618.bingfaqimenv2'
    compileSdk 36

    defaultConfig {
        applicationId 'com.abe618.bingfaqimenv21fix'
        minSdk 23
        targetSdk 34
        versionCode 30
        versionName '2.1.0'
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
