plugins { id 'com.android.application' }

android {
    namespace 'com.abe618.footballfusion.v13'
    compileSdk 36
    defaultConfig {
        applicationId 'com.abe618.footballfusion.v13'
        minSdk 26
        targetSdk 36
        versionCode 14
        versionName '1.4.0'
    }
    buildTypes {
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
