plugins {
    id 'com.android.application'
}

android {
    namespace 'com.abe618.footballfusion.v13fix'
    compileSdk 36

    defaultConfig {
        applicationId 'com.abe618.footballfusion.v14oufix'
        minSdk 26
        targetSdk 36
        versionCode 16
        versionName '1.4.1-oufix'
    }
}
