plugins {
    id 'com.android.application'
}

android {
    namespace 'com.abe618.footballfusion.v13fix'
    compileSdk 36

    defaultConfig {
        applicationId 'com.abe618.footballfusion.v14three'
        minSdk 26
        targetSdk 36
        versionCode 15
        versionName '1.4-three-button'
    }
}
